#!/bin/sh
set -e

# Directory for SSL certs
SSL_DIR="/etc/nginx/ssl"
mkdir -p "$SSL_DIR"

# Check if certificates exist
if [ ! -f "$SSL_DIR/server.crt" ] || [ ! -f "$SSL_DIR/server.key" ]; then
    echo "⚠️  SSL certificates not found in $SSL_DIR"
    echo "Generating self-signed certificate for localhost..."
    
    # Generate self-signed certificate
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout "$SSL_DIR/server.key" \
        -out "$SSL_DIR/server.crt" \
        -subj "/C=ES/ST=Local/L=Local/O=AutoGenerated/CN=localhost"
        
    echo "✅ Certificate generated successfully."
else
    echo "✅ SSL certificates found."
fi

# Start Nginx
echo "Starting Nginx..."
exec nginx -g "daemon off;"
